name: CI setup for build pages

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 8.6.12
    - name: "Install Node.js"
      uses: actions/setup-node@v3
      with:
        node-version: 18.15.0
        cache: 'pnpm'
    - name: "Install root dependencies"
      run: pnpm install
      shell: bash
